#! /usr/bin/env python

import sys
from os.path import expanduser
import argparse
import csv

def ls(args):
    with open(args.csvfile) as f:
        reader = csv.reader(f)
        for row in reader:
            print row[0]

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--csvfile', type=expanduser,
                   default='~/Me Own Knowledge Base.csv')
    subs = p.add_subparsers()

    pl = subs.add_parser('ls')
    pl.set_defaults(func=ls)


    args = p.parse_args()

    args.func(args)


if __name__ == '__main__':
    sys.exit(main())
