#! /usr/bin/env python

import sys
import argparse
import csv

def main():
    p = argparse.ArgumentParser()
    p.add_argument('csvfile')
    args = p.parse_args()

    with open(args.csvfile) as f:
        reader = csv.reader(f)
        for row in reader:
            print row[0]

if __name__ == '__main__':
    sys.exit(main())
